backend:
  name: github
  repo: dthomson12/KarynWebsite
  branch: main

media_library:
  name: default

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: galleries
    label: Galleries
    folder: content/galleries
    create: true
    slug: "{{slug}}"
    format: frontmatter
    extension: md
    identifier_field: title
    summary: "{{title}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
        required: false
      - label: Images
        name: images
        widget: list
        allow_add: true
        collapsed: false
        summary: "{{fields.image}}"
        fields:
          - label: Image File
            name: image
            widget: image
          - label: Alt Text
            name: alt
            widget: string
            required: false
          - label: Caption
            name: caption
            widget: string
            required: false
          - label: Title Tag
            name: title_tag
            widget: string
            required: false
          - label: Description
            name: description
            widget: text
            required: false
